# https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
external-dns:
  provider: cloudflare
  cloudflare:
    secretName: external-dns-secrets
    proxied: true
  policy: upsert-only
  domainFilters:
    - pastis-hosting.net
