# https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
external-dns:
  provider: cloudflare
  cloudflare:
    apiToken: "<secret:kv/data/pastis-hosting.net/cloudflare~api_token|base64>"
    proxied: true
  policy: upsert-only
  domainFilters:
    - pastis-hosting.net
