apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-traefik
  project: default
  source:
    chart: traefik
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
        ingressRoute:
          dashboard:
            enabled: false
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        additionalArguments:
          - "--entryPoints.web.proxyProtocol.insecure=true"
          - "--entryPoints.web.forwardedHeaders.insecure=true"
          - "--entryPoints.websecure.proxyProtocol.insecure=true"
          - "--entryPoints.websecure.forwardedHeaders.insecure=true"
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.6.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
