helm:
  chart: traefik
  repoURL: https://helm.traefik.io/traefik
  targetRevision: 10.6.2
  values: |
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.insecure=true"
      - "--entryPoints.web.forwardedHeaders.insecure=true"
      - "--entryPoints.websecure.proxyProtocol.insecure=true"
      - "--entryPoints.websecure.forwardedHeaders.insecure=true"