traefik:
  deployment:
    replicas: 3
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"
rollingUpdate:
  maxUnavailable: 0

traefik-forward-auth:
  default:
    provider: oidc
  cookie:
    domain: .pastis-hosting.net
  middleware:
    enabled: true
  providers:
    oidc:
      enabled: true
      issuerUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      clientId: traefik
      clientSecret: 5qcAAVXRkG5F5AtCsloXnP1TnQxIJry4
    genericOauth:
      enabled: false
      authUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      tokenUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net/protocol/openid-connect/token
      userUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net/protocol/openid-connect/userinfo
      clientId: traefik
      clientSecret: 5qcAAVXRkG5F5AtCsloXnP1TnQxIJry4
      scope: profile, email
      tokenStyle: access_token
