traefik:
  deployment:
    replicas: 1
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"
rollingUpdate:
  maxUnavailable: 0

traefik-forward-auth:
  logging:
    level: debug
  authHost: auth.traefik.pastis-hosting.net
  # urlPath: /dashboard/
  default:
    provider: oidc
  cookie:
    domain: .pastis-hosting.net
    insecure: true
  middleware:
    enabled: false
    name: traefik-forward-auth
  providers:
    oidc:
      enabled: true
      issuerUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      clientId: traefik
      clientSecret: hRjBDv4TYC3vfXS1tIiU7DFDMR8nwsF2
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: auth.traefik.pastis-hosting.net
    hosts:
      - host: auth.traefik.pastis-hosting.net
        paths:
          - /
