traefik:
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"