traefik:
  deployment:
    replicas: 1
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"
rollingUpdate:
  maxUnavailable: 0

traefik-forward-auth:
  default:
    provider: oidc
  cookie:
    domain: .pastis-hosting.net
    unsecure: true
  middleware:
    enabled: true
    name: traefik-forward-auth
  providers:
    oidc:
      enabled: true
      issuerUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      clientId: traefik
      clientSecret: 5qcAAVXRkG5F5AtCsloXnP1TnQxIJry4
  urlPath: /dashboard/
