traefik:
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    subPath: "traefik"
    size: 1Gi
  securityContext:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
    runAsNonRoot: false
  deployment:
    replicas: 1
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"
    - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    - "--certificatesresolvers.cloudflare.acme.email=tristan@jeancloude.club"
    - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1"
    - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
  env:
    - name: CF_API_EMAIL
      value: contact@constructions-incongrues.net
    - name: CF_API_KEY
      value: BYR8IAr6DNRc5JfUZtGtirRzLJV-XMJAfwYjIKHK
  ports:
    web:
      redirectTo: websecure
rollingUpdate:
  maxUnavailable: 0

traefik-forward-auth:
  logging:
    level: debug
  authHost: auth-traefik.pastis-hosting.net
  default:
    provider: oidc
  cookie:
    domain: pastis-hosting.net
    insecure: true
  middleware:
    enabled: false
    name: traefik-forward-auth
  providers:
    oidc:
      enabled: true
      issuerUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      clientId: traefik
      clientSecret: hRjBDv4TYC3vfXS1tIiU7DFDMR8nwsF2
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: auth-traefik.pastis-hosting.net
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
    hosts:
      - host: auth-traefik.pastis-hosting.net
        paths:
          - /
    tls:
    - hosts:
      - auth-traefik.pastis-hosting.net
      secretName: traefik-forward-auth-ingress