traefik:
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"

traefik-forward-auth:
  default:
    provider: oidc
  cookie:
    domain: .jeancloude.club
  providers:
    oidc:
      enabled: true
      issuerUrl: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      clientId: traefik
      clientSecret: blpGQIb6ccCZgc1D8ZFYbSIxu1l9nA09

  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: trfk.pastis-hosting.net
    hosts:
      - host: trfk.pastis-hosting.net
        paths:
          - /