#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

homer:
  # -- environment variables.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: Europe/Paris

  ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
    main:
      # -- Enables or disables the ingress
      enabled: true

      # -- Provide additional annotations which may be required.
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
        external-dns.alpha.kubernetes.io/hostname: www.pastis-hosting.net
        traefik.ingress.kubernetes.io/router.tls: "true"

      ## Configure the hosts for the ingress
      hosts:
        -  # -- Host address. Helm template can be passed.
          host: www.pastis-hosting.net

          ## Configure the paths for the host
          paths:
            -  # -- Path.  Helm template can be passed.
              path: /

      # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
      tls:
       - secretName: homer-tls
         hosts:
           - www.pastis-hosting.net

  configmap:
    config:
      # -- Store homer configuration as a ConfigMap
      enabled: true
      # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
      # @default -- See values.yaml
      data:
        config.yml: |
          title: "Pastis Hosting"
          subtitle: "L'Affreux Pastis de la Rue des Gardes"
          icon: "fab fa-glass"

          header: false # Set to false to hide the header

          columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
          connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

          # Optional navbar
          links:
            - name: "Constructions Incongrues"
              url: "https://www.constructions-incongrues.net"
              target: "_blank"
            - name: "Club Jean-Cloude"
              url: "https://www.jeancloude.club"

          # Services
          # First level array represents a group.
          # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
          services:
            - name: "Administration"
              icon: "fas fa-wrench"
              items:
                - name: "État des services"
                  icon: "fas fa-lock-open"
                  url: "https://status.pastis-hosting.net"
                  target: "_blank"
                - name: "ArgoCD"
                  icon: "fas fa-lock"
                  url: "https://argocd.pastis-hosting.net"
                  target: "_blank"
                - name: "K10"
                  icon: "fas fa-lock"
                  url: "https://k10.pastis-hosting.net/k10/"
                  target: "_blank"
                - name: "Keycloak"
                  icon: "fas fa-lock"
                  url: "https://keycloak.pastis-hosting.net"
                  target: "_blank"
                - name: "Prometheus"
                  icon: "fas fa-lock"
                  url: "https://prometheus.pastis-hosting.net"
                  target: "_blank"
                - name: "Traefik"
                  icon: "fas fa-lock"
                  url: "https://trfk.pastis-hosting.net/dashboard/"
                  target: "_blank"
                - name: "Vault"
                  icon: "fas fa-lock"
                  url: "https://vault.pastis-hosting.net"
                  target: "_blank"
