apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-argocd
  project: platform
  source:
    path: src/charts/argocd
    repoURL: https://github.com/constructions-incongrues/club.jeancloude.k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true