# https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
argo-cd:
  global:
    image:
      tag: 'v2.3.0-rc5'
  installCRDs: true
  dex:
    enabled: false
  repoServer:
    serviceAccount:
      create: true
      name: argocd-repo-server
    extraArgs:
      - '--parallelismlimit'
      - '2'

    volumes:
    - name: custom-tools
      emptyDir: {}

    volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/argocd-vault-replacer
      subPath: argocd-vault-replacer
    envFrom:
      - secretRef:
          name: argocd-vault-replacer-credentials

    initContainers:
    - name: argocd-vault-replacer-install
      image: ghcr.io/crumbhole/argocd-vault-replacer
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argocd.pastis-hosting.net
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
        clientID: argocd
        clientSecret: Evc9Sx9x5pktvCFsFdFNhn0RhCXGeJZi
        requestedScopes: ["openid", "profile", "email", "groups"]
    rbacConfig:
      policy.csv: |
        g, argocd:admins, role:admin
    ingress:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      tls:
      - hosts:
        - argocd.pastis-hosting.net
        secretName: argocd-ingress-cert
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
        cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
        traefik.ingress.kubernetes.io/router.tls: "true"
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      tls:
      - hosts:
        - argocd.pastis-hosting.net
        secretName: argocd-ingress-cert
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
        cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
        traefik.ingress.kubernetes.io/router.tls: "true"
