apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-argocd
  project: platform
  source:
    path: src/projects/platform
    repoURL: https://github.com/constructions-incongrues/club.jeancloude.k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
