apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: deploy/kubernetes/snapshot-controller
    repoURL: 'https://github.com/constructions-incongrues/external-snapshotter'
    targetRevision: release-5.0
  project: system.snapshots
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
