apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: token
  AVP_VAULT_TOKEN: s.VVztwjEdhI0rTcAbSkqpcfqE
  VAULT_TOKEN: s.VVztwjEdhI0rTcAbSkqpcfqE
  AVP_TYPE: vault
  VAULT_ADDR: vault-internal.ph-vault
