traefik:
  logs:
    general:
      level: DEBUG
  persistence:
    enabled: true
  securityContext:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
    runAsNonRoot: false
  deployment:
    replicas: 1
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure=true"
    - "--entryPoints.web.forwardedHeaders.insecure=true"
    - "--entryPoints.websecure.proxyProtocol.insecure=true"
    - "--entryPoints.websecure.forwardedHeaders.insecure=true"
    - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    - "--certificatesresolvers.cloudflare.acme.email=tristan@pastis-hosting.net"
    - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1"
    - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
  env:
    - name: CF_API_EMAIL
      valueFrom: 
        secretKeyRef:
          name: traefik-secrets"
          key: cloudflare_api_email
    - name: CF_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: traefik-secrets"
          key: cloudflare_dns_api_token
  ports:
    web:
      redirectTo: websecure
rollingUpdate:
  maxUnavailable: 0

traefik-forward-auth:
  env:
    TZ: Europe/Paris
    COOKIE_DOMAIN: pastis-hosting.net
    DEFAULT_PROVIDER: oidc
    PROVIDERS_OIDC_ISSUER_URL: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
    PROVIDERS_OIDC_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: "traefik-secrets"
          key: providers_oidc_client_id
    PROVIDERS_OIDC_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: "traefik-secrets"
          key: providers_oidc_client_secret
