apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-kasten
  project: jeancloude.club
  source:
    chart: k10
    helm:
      values: |
        auth:
          basicAuth:
            enabled: true
            htpasswd: "tristan:{SHA}K+iK4HpzuMKnVlbTaxQSkD9/eLg="
        ingress:
          create: true
    repoURL: https://charts.kasten.io/
    targetRevision: 4.5.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
