apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: icekubes-location-objectstore-de
  namespace: platform-kasten
  labels:
    argocd.argoproj.io/instance: kasten
    app.kubernetes.io/instance: kasten
    app.kubernetes.io/name: kasten
spec:
  locationSpec:
    credential:
      secret:
        apiVersion: v1
        kind: secret
        name: icekubes-aws
        namespace: platform-kasten
      secretType: AwsAccessKey
    objectStore:
      endpoint: https://s3.de.cloud.ovh.net
      name: kasten
      path: net.pastis-hosting.icekubes
      objectStoreType: S3
      pathType: Directory
      region: DE
    type: ObjectStore
  type: Location
