apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
    external-dns.alpha.kubernetes.io/hostname: keycloak.pastis-hosting.net
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: keycloak.pastis-hosting.net
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - keycloak.pastis-hosting.net
    secretName: keycloak-ingress
