apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: system.expose
  source:
    chart: external-dns
    helm:
      values: |
        policy: sync
        provider: cloudflare
        cloudflare:
          apiToken: 3nvKsWWxkuc2Wc1oh73rEi6t0XH4QfuMaQQ2lN4g
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true