apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    admin-password: AgCOSBFMfyKENZAIy/cJ1DWAdG8K4QKtAMeoZ4B0D9eUBg9omgHMvaK1KBZ09hK//2Lv5+9cvmezf4LawdJoEjvm7VGBR4NEJuECFolROH/i5Xj1HULDRIjwUG9jC9LO3cp97OhACyroM4fc1MkUFQVxaVTeVwAaHX1RRCf4Am7NZUUfnUg9O1xvbS4UzHUrofKl86OTDLl0ooOT2gBb73dtpsoFdVSaWwxgYJd7OUJUzes6Kioud9Y5T+62asDRyieQeefNFofIfg+nzBlA9EH5Me+aajB6ag+4zSyqLG4095YaHCiUaG9hnbkB3sYPYbtE3Z6gtlbMIokk7WHYIdn97vPwC2H9Uec2/Nyv4lXtl3RFreEIZHBSCVw2y1GDqSRKBtAJtrp0KvrEozrjvxyR4BqlahcHidyVe80bYFKm6Kofk4+QYGMiYE8mo9bed8ZVWYRiy+anF1kuW8vJecDYSJpQi4eniXs6cBiIj4CNOg1AwB/+O5aXQUog/TvGMAE+1VbcNLJwt/WIBN09R+FaA3GbH5zpnur4WSMxiZq5DCz58DhHI0kBqv97NCSypsMD9uG2pI4u22QQLcMNvITTPu07Cge4850NRU5Izciv/0Gt6d5rzLQO+WfdzROAkUpQeAF3GxKpDN4SUPotuQ3xB5xVB1s7ehipBc3oAIHJIoqvNfrVf1tUJCVKyZ9ga10xjnCfAWcW6HIUIUjcuw07ojlpHJceNbMdvs6pO2tsmw==
    password: AgCD9z7nnjXuOS2klW11q3JRumUEeBofkdnLu/us4YoPoX8kqTOTuStvdOMyaef1WfBoLOig4NH8goa1nXfVLkDMgiNrN75Swzwl85XlJdwXv10T7VFHcgA+xGOS+mM18gJ5mPtlcvmm7jHQZc7Z04If/labJg+RPPb9Akswua2g5jajEX0eFXDqe8yuggrc+EZlwUL+AsugTL+Vcrqa4OIHYwsgmRtLTuJNrs1wjLxxszOVeyQP5zknzcsvfvn+CxfKwEq6fbfPg0vHHROP9usSWrB704r/PZzgELz1Lin3XjgVSut1Ki0f5769akZM+fzidCzL6L1HHmIb+z8r1HC9LJ2i2KARDctjt6zVvEaKiAK8XaD61tLOYa4YhU2SjZ3YQjm+t7qjOpGBsa9N4bMqD+QSBnsqkAvu32ENx+zbFBMH/KsSpeoMWkg1fD3qFMO7qxcE8ZYjtCQyabJ3dtD+D29S7PzBMUeVG8WtjFDJSJu3190/1BHu8hkpJQC06g9afftjev6WlYXXoY2JdwrR/48FtiDAY5SNmSmu9Ug7vt1Pc0SpEVNrVX/KXq/5e+HummW+v93e1aFnPacodPHmYfvsDfID+R0KJYwvlxXWUr/CV/+BFz3P98fN+FAv6vpOhyeAIRo72rjn7PUl7vOBujNXPqFWylpkRE9wvILvtVP4RB2eB01/d/KiY1of6bsoUuawcQY9rNOKmx9Q06hbDZ1IXj5hpESJ7EMsRXMQJg==
    username: AgAjh3AAsZ9g721QIBuh/kPzVzqTUEqvmXCgCRTZ0mAggWaauTTvGyodCgC1X6UN7nC3373Io59jJnH8KILZlgesERlPhDFaH/2bpqTwLHOskHVPmi/XSvRtYAC4A/DSjQD1bZ6TthmJSZaaJKalLrXZD38cAI9AyMOjvnUPypIUFbu3qcCO/xituztBU4XhSrQbtAqjQ7ANRaC2pj5g9ipHEGkHy4cZy+ULDrbxDe3xO7SeFhh8a49iZipKqVEpbqswwIVAxAA889u0aF0IeDWckEzVAKupyuVCRA11UVE4/IOMMsE6Qw51shX00lh3jFgyspHUvB82rEbjNC1QLkaWVN2ZiI52g55yo8P2zdLDD9C5kCJU/L8vePX+sBCPw0g9ctRVamn5fVKJIs+U8KItpyc9etwKtRdnN+ttjg3FCWWUv8jmWneV+QnBy20HHxilZX5ppCofP13s8cmr7bsJBYy6EgdU53hG2pi7EixjcuO4FvGYiIV486/sc0K5eHRgJ1QGxhsaNOJc7GKGW90pWZ7RnN9/McRMQabmZi9YUdruXKZsC0v1j6d3hVfzmsHODozMFF6563CRJ2v6xQZvj0S0rTEpuyr0lqb+H88Qcur9kazhzAjiWuO7XHutc1Dqohs8LedVKEHVD005GenOY3SROtUhlPOJYqz/1KobOKhCJ8y5BAHR5ZDUdi8LJFxM490gqJ1daA==
  template:
    data: null
    metadata:
      labels:
{{ include "helm.labels" . | indent 8 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets


    
