apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    password: AgAPSLoMeyrbG0PXeT3650AoJrFWvtXx19tuZcnZod5JpSL3SIZuGJnObZCfWA86Tf1F4Gji1iIEk0taah6/IpedQrvDfMd7SfhhM0V5Phz61nL9y6WmHunu6B0Nlk5TOVu/ls99NrqT5K2zjop8BoU6/uaJEAfDhKp9kocS0RG/hoICRMlcjJaU5g3FkENu9GeZLhmwN3jrQQUmL6A96tQhdH0q4XT1KiXgQhoSr59kTdaZ3hhY67DPnC1jw4g838fELWwZYVWjTvN0LpxIHsDIxjd93Qb7t4aK62dVPEgEEtCJ4HafsRyKh7u/jxHlgLM+8WVVHFWR88rhsmCGOn+vqyo24krW+ACnmBPGRSSF7CTAnBWM0f8kf9b4wrq7NRLzPOOo8He0BQAbmisxFUWDlUSnbYCoK7C5yAGaCOT7YzkYpWvkIz5zs3AsTNF0SiDrQxRLUPhVXAGbvk02HOSKKzZTtEGWJGP2Zet1MNRjF/G6CZykptzvQE5EFT43VnoJ4GorbxVi2mM3gLWzYyVlm0mD1S9lJd4h4rdAg/SPF4Y4HIK4EeSOhxiWg8iBA8cSqNxid0C5gvE+gbpn1nRkYFmgeQS6SKwNOlCmGnk3B8KaI3Un3du0CA/MeMUcpuYA2Bte7Q3gMl+nWgU4hmJdv4K5snEr6G8VSPCVP31DIHyNW/CsEg0SZGTWYoyVoJKAne8soegI+QBTOTLDGQ==
    username: AgAVt3lc0hhalUZLwAoEjQZyShymG25FsEtyxzbLxwz4LHHdYTXCR9vU2aCt+qOK0Rhor6fqaYZwEIq7r8SgOO+V8GRlMLoepKQDFfZ9cWvjtWJwbc1gW+bbp6dtWy03n0Eia5tnJhkDjVi/4CQbTegr+3c1FcqE8b59Tg43GyT+pAEalZ3mwsew0pD65HCeW7vEtzIj4lcRAknLUiAde80LSrGRq6aonpxiV13ck3zhcRepf1IJpzrBaU16zlOVCCIfN7vrRHoQU4R1oonIRyw1dFhwEawbzbpv+goO79cmfH8QZMfGQR9hX6GZLi7E1gFxwrDVSKKOijDjVTx4lEyL4n8U4ivoL0r5l3tyaVfV5MNPADtux6TpSggAVHVZ1GDBHDmi/sBIJvOUj7RIbtnwuvlex81BpVru1zI9DTRWHqXHkBdVnmGF7ErZfq0uq6klrZLfxs4qNPh/8iJXoelbA0X8GT8uTpoVqVAlaxgCmAtfOo/ZNVEYajH79zZs4w2/6lP370rdUffMIT0ohbN7R3CozSdnTZS6a7q5/asJcnC7HFbBIMYTBKeiajiUk947oWK+qLQHxFxxA6Nm8X4FSW1SrpBYOOgBRLjyzadeUgM+kImILrEChCW/TpdXJPm96IBPUjOM7ak4HDaogweNMsK8PouPeoZ6I3gu4dqC2eI61iZUGdvytFtykcH539Y3pYent3kDmQ==
  template:
    data: null
    metadata:
      labels:
    {{ include "helm.labels" . | indent 6 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets


    
