apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    password: AgAlljShqfIFC7DEJ1svQuhZr5zHM9TOW6TjjwQ0MBb3S4O5rkmonPKQC3iQpFNVXVr7ZC2DZStH7RSMBOJNjnNCvbpOgGgTTAUeuifHSEshK5U40uwLNq1U/+MY6cxFxnCi6a9I5+tM1T+IgfcZ+GfHK4cHteYQWXsRJzufC3Hpy51dPXWIzxmZi6Ijvtx+U0m/XnBvlTmIghhjMS/fh/wn82V73dhPEuFWofG9K3J3ACBJ5H6HMcDcXTpQVQ7F5rC54Bjm8xq00Yw83MUNNF9CES3oQVixA9W+mYn3jYRlktWmoLAjPGdOCs9o6sVRQS+qoZI1Tm2vEorFOwe6x+YXQEfH+ifef6TFFZo0t5DjVtGECo23HUaJgHvuvQ3xMW855N8VrRsWclXBACpRm0s7o1+Vwq3/m817WzEcpR2l+vmyJeTeKUo1N0Mh5Vc+tz8BhnHIMD4oKpZNXTCOQ18AwaD0iJ3FWUJzFF3J2vt+FRS4G75YKlRUNgJq3x8io+hjL+iaiJ4EBjrhd3W+rfeOZjt1HMfR5Wv6rgxbP5QwsTVODigkE/efwWGtTnT9q4RRztj8s09wgn7nIrEWWEEcpEeIyMusGBYDVmcxA2psL4tKQAjvmSFXFGUHflQteXhmjMb6tvDfelQ3/UzT/5QSq0njUfn5+pJJf/o837G5ctuwwgaEY6C0BEol/R3jvKhc4UBmoPPMINtZ4rEQ5viSS681fwQ6MjGNIjP8ZeNQVCbF0RKaGOqP
    username: AgA+kGPkKHQcYQ+R6P9V27r5MfNeVnR4gY9n2sXKZjBthN2ftPxF+zOEEC9C0K8FmYRyWKO2SJfVBR/PmOb5gZUQRJssYnzgywwq5GFMNqm/n+OZOLf02gqfdoYLS78uJ9Oq2op0wgr/kK+bJ9SPVlZgXWaO40TUQJrrLfOR9L8LkU1ZXPI5jsuZU2W9NOOMTOXgLpd2aei8cCyggMJa/ZxHL07TzBttt+21imeWPeH/8yW87rNq055EzoG7h/XMhZFKzgle85Lm/TM/Guf8z4gvwqlt/cebIPSKTtLsB+Z6G7ZmU7t+aP+KUvHeDlpXNF3Wi+/nMUVasEr57MNqEke7cytQ0jOVgS5eUSuJubbQENtgtobyIqxvV0TJDuAcrOhN4PL3/q5KpYgu2i9J5dZpZLOZWTftgd7fR4DXfJcBNj5g4IYoJ+6Bw39k2W7P50DdeOWE8HWLL0sQUanH0AeDZweLlnEW0WOdrHIwMyFkmVeUXwGvwQQgFz1GEPcQMrxOAZwPoxfI/2wPG6aWmN5YOxmmGbTz2J6M6MpUsbl+hukVsCXxdFvGYJ1B/Md+petjb4D+XVpSqlLK1Ax0wQIw+J1CPDr4EAhv9U3Mof84piNz2dDGkSuPEbUQa6HPhbZa7cTvHRC5VSpJID69+HUwxtLMvcfqH5Hl6Nd7m4M9ekm8ulzXW1+USji7vtnWKMMr+CX38m2ong==
  template:
    data: null
    metadata:
      labels:
{{ include "helm.labels" . | indent 8 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets


    
