apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-cloud-controller-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: system.snapshots
  source:
  source:
    path: charts/openstack-cloud-controller-manager
    helm:
      values: |
        controllerExtraArgs: |-
          - --cluster-name=Icekubes
        cloudConfig:
          global:
            auth-url: https://auth.cloud.ovh.net/v3/
            username: user-xUukp5UXvZyp
            password: vGdHXCW49Rt8BrfaDWVSWkVaSKgCMAnz
            tenant: 8966606530353673
            domain: Default
            region: GRA5
          loadbalancer:
            create-monitor: true
        secret:
          create: true
          name: openstack-cloud-controller-manager-cloud-config
    repoURL: 'https://github.com/kubernetes/cloud-provider-openstack'
    targetRevision: v1.22.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
