apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    chart: argo-cd
    server: https://kubernetes.default.svc
    namespace: platform-argocd
  project: platform
  source:
    helm:
      values: |
        installCRDs: true
        dex:
          enabled: true
        server:
          extraArgs:
            - --insecure
          config:
            repositories: |
              - type: helm
                name: stable
                url: https://charts.helm.sh/stable
            url: https://argocdpastis-hosting.net
          ingress:
            enabled: true
            hosts:
              - argocdpastis-hosting.net
            annotations:
              external-dns.alpha.kubernetes.io/hostname: argocdpastis-hosting.net
          ingressGrpc:
            enabled: true
            hosts:
              - argocdpastis-hosting.net
            annotations:
              external-dns.alpha.kubernetes.io/hostname: argocdpastis-hosting.net
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.13.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true