argo-cd:
  installCRDs: true
  dex:
    enabled: true
    extraArgs: [--parallelismlimit 1]
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
      url: https://argocd.pastis-hosting.net
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
    ingress:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
