argo-cd:
  installCRDs: true
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
      url: https://argocd.pastis-hosting.net
    ingress:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
