# https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
argo-cd:
  global:
    image:
      tag: 'v2.3.0-rc5'
  installCRDs: true
  dex:
    enabled: false
  repoServer:
    extraArgs:
      - '--parallelismlimit'
      - '2'
    volumes:
    - name: custom-tools
      emptyDir: {}
    initContainers:
    - name: download-tools
      image: alpine:3.8
      command: ["sh", "-c"]
      args:
        - "wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.8.0/argocd-vault-plugin_1.8.0_linux_amd64 && apk add --update coreutils && chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/"
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    volumeMounts:
    - mountPath: /usr/local/bin/argocd-vault-plugin
      name: custom-tools
      subPath: argocd-vault-plugin
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argocd.pastis-hosting.net
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
        clientID: argocd
        clientSecret: Evc9Sx9x5pktvCFsFdFNhn0RhCXGeJZi
        requestedScopes: ["openid", "profile", "email", "groups"]
      configManagementPlugins: |-
        - name: argocd-vault-plugin-helm
          init:
            command: ["sh", "-c"]
            args: ["helm dependency build"]
          generate:
            command: ["sh", "-c"]
            args: ["helm template $ARGOCD_APP_NAME . > all.yaml && argocd-vault-plugin generate all.yaml"]
    rbacConfig:
      policy.csv: |
        g, argocd:admins, role:admin
    ingress:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      tls:
      - hosts:
        - argocd.pastis-hosting.net
        secretName: argocd-ingress-cert
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
        cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
        traefik.ingress.kubernetes.io/router.tls: "true"
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      tls:
      - hosts:
        - argocd.pastis-hosting.net
        secretName: argocd-ingress-cert
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
        cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
        traefik.ingress.kubernetes.io/router.tls: "true"
