argo-cd:
  installCRDs: true
  dex:
    enabled: false
  repoServer:
    extraArgs:
      - '--parallelismlimit'
      - '3'
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
      url: https://argocd.pastis-hosting.net
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
        clientID: argocd
        clientSecret: Evc9Sx9x5pktvCFsFdFNhn0RhCXGeJZi
        requestedScopes: ["openid", "profile", "email", "groups"]
    rbacConfig:
      policy.csv: |
        g, argocd:admins, role:admin
    ingress:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.pastis-hosting.net
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.pastis-hosting.net
