apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: ph-argocd
  name: pastis-hosting
spec:
  generators:
  - git:
      repoURL: https://github.com/constructions-incongrues/net.pastis-hosting.k8s.git
      revision: HEAD
      directories:
      - path: src/applications/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
      namespace: '{{ Release.Namespace }}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: pastis-hosting
      source:
        repoURL: https://github.com/constructions-incongrues/net.pastis-hosting.k8s.git
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{ Release.Namespace }}-{{ path.basename }}`}}'
