---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Le Cloude est dans l'hébergerie

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system.snapshots
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: 

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system.cd
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: 

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system.expose
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: 

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services.allo
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: 

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services.cartemembre
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: 

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services.club
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: 

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - kind: '*'
    group: '*'