apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Name }}-{{ .Values.profiles.infrastructure }}
  namespace: ph-k10
spec:
  infra:
    credential:
      secret:
        apiVersion: v1
        kind: secret
        name: {{ .Release.Name }}-{{ .Values.profiles.infrastructure }}
        namespace: ph-k10
      secretType: GcpServiceAccountKey
    type: GCP
  type: Infra