vault:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
        external-dns.alpha.kubernetes.io/hostname: vault.pastis-hosting.net
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - vault.pastis-hosting.net
      tls:
      - hosts:
        - vault.pastis-hosting.net
        secretName: vault-ingress-cert