keycloak:
  serviceAccount:
    name: keycloak
  rbac:
    create: true
  replicaCount: 2
  serviceDiscovery:
    enabled: true
    protocol: dns.DNS_PING
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/config/realms.json"
  extraVolumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: "{{ .Release.Name }}-realms-cm"
        items:
        - key: "realms.json"
          path: "realms.json"
  auth:
    createAdminUser: true
    adminUser: admin
    adminPassword: admin
  proxyAddressForwarding: true
  postgresql:
    postgresqlPassword: keycloak
    postgresqlPostgresPassword: keycloak
    persistence:
      enabled: true
      size: 1Gi
    volumePermissions:
      enabled: true
    primary:
      annotations:
        k10.kasten.io/forcegenericbackup: 'true'
      labels:
        k10.kasten.io/injectKanisterSidecar: 'true'
  service:
    type: ClusterIP
    annotations:
      traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      traefik.ingress.kubernetes.io/service.sticky.cookie.name: '{{ .Release.Name }}'
      traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"