apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://traefik-traefik-forward-auth.ph-traefik:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
