kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: icekubes
  namespace: kasten-io
  labels:
    argocd.argoproj.io/instance: kasten
    app.kubernetes.io/instance: kasten
    app.kubernetes.io/name: kasten
spec:
  infra:
    credential:
      secretType: OpenStackAccount
      secret:
        apiVersion: v1
        kind: secret
        name: icekubes-openstack-de
        namespace: kasten-io
    openStack:
      keystoneEndpoint: https://auth.cloud.ovh.net/v3/
    type: OpenStack
  type: Infra
