apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jeancloude.club
  namespace: default
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Le Cloude est dans l'hébergerie

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace