apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-keycloak
  project: jeancloude.club
  source:
    chart: keycloak
    helm:
      values: |
        image:
          tag: 15.0.2
        clusterDomain: kubernetes.default.svc
        extraEnv: |
          - name: PROXY_ADDRESS_FORWARDING
            value: 'true'
        ingress:
          enabled: true
          rules:
            -
              host: 'cm.jeancloude.club'
              paths:
                - path: /
                  pathType: Prefix
            -
              host: 'cartemembre.jeancloude.club'
              paths:
                - path: /
                  pathType: Prefix
          console:
            enabled: true
            rules:
              -
                host: 'cm.jeancloude.club'
                paths:
                  - path: /auth/admin/
                    pathType: Prefix

    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 15.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true