apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-kubecost
  project: jeancloude.club
  source:
    chart: cost-analyzer
    helm:
      values: |
        kubecostToken: dHJpc3RhbkByaXZvYWxsYW4ubmV0xm343yadf98
        ingress:
          annotations:
            kubernetes.io/ingress.class: traefik
          enabled: true
          hosts:
            - kubecost.jeancloude.club
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 1.88.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
