apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: jeancloude.club
  source:
    chart: longhorn
    helm:
      values: |
        ingress:
          enabled: true
          host: longhorn.jeancloude.club
        csi:
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1
    repoURL: https://charts.longhorn.io
    targetRevision: 1.2.3
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
