apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-nextcloud
  project: jeancloude.club
  source:
    chart: nextcloud
    helm:
      values: |
        image:
          tag: 23.0.0-fpm
        cronjob:
          enabled: true
        internalDatabase:
          enabled: false
        mariadb:
          enabled: true
        nginx:
          enabled: true
        persistence:
          enabled: true
        nextcloud:
          host: app.jeancloude.club
          configs:
            logging.config.php: |-
              <?php
              $CONFIG = [
                'log_level' => 2,
                "log_type" => "errorlog",
              ];

            objectstore.config.php: |-
              <?php
              $CONFIG = [
                'objectstore' => [
                  'class' => 'OC\\Files\\ObjectStore\\Swift',
                  'arguments' => [
                    'autocreate' => 'true',
                    'user' => [
                      'name' => 'user-KPNf2CXgFmYY',
                      'password' => 'ChaDQNt8R6CpWeaHfDNeWmzd6edhDmwW',
                      'domain' => [
                        'name' => 'Default',
                      ]
                    ],
                    'tenantName' => '8966606530353673',
                    'serviceName' => 'swift',
                    'region' => 'GRA',
                    'url' => 'https://auth.cloud.ovh.net/v3/',
                    'bucket' => 'club-jeancloude-nextcloud_01',
                    'scope' => [
                      'project' => [
                        'name' => 'de9eaa1e9cc94734bf787165a68f4d01',
                        'domain' => [
                          'name' => 'Default',
                        ],
                      ],
                    ],
                  ],
                ],
              ];

            preview.config.php: |-
              <?php
              $CONFIG = [
                'filelocking.enabled' => true,
                'enable_previews' => true,
              ];

            proxy.config.php: |-
              <?php
              $CONFIG = [
                'overwriteprotocol' => 'https',
                'overwrite.cli.url' => 'https://app.jeancloude.club',
                'trusted_domains' => [
                  'nextcloud',
                  'app.jeancloude.club'
                ]
              ];

        ingress:
          enabled: true
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 2.10.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true