apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-nextcloud
  project: jeancloude.club
  source:
    chart: nextcloud
    helm:
      values: |
        image:
          tag: 23.0.0-apache
        replicaCount: 1
        cronjob:
          enabled: true
        internalDatabase:
          enabled: false
        mariadb:
          enabled: true
          architecture: standalone
          primary:
            persistence:
              enabled: true
        nginx:
          enabled: false
        persistence:
          enabled: true
        redis:
          enabled: true
        nextcloud:
          host: app.jeancloude.club
          configs:
            caching.config.php: |-
              <?php
              $CONFIG = [
                'memcache.local' => '\OC\Memcache\APCu',
                'memcache.distributed' => '\OC\Memcache\Redis',
                'memcache.locking' => '\OC\Memcache\Redis',
                'redis' => [
                  'host' => getenv('REDIS_HOST'),
                  'port' => getenv('REDIS_HOST_PORT') ?: 6379,
                  'password' => getenv('REDIS_HOST_PASSWORD')
                ]
              ];

            objectstore.config.php: |-
              <?php
              $CONFIG = [
                'objectstore' => [
                  'class' => 'OC\\Files\\ObjectStore\\Swift',
                  'arguments' => [
                    'autocreate' => 'true',
                    'user' => [
                      'name' => 'user-KPNf2CXgFmYY',
                      'password' => 'ChaDQNt8R6CpWeaHfDNeWmzd6edhDmwW',
                      'domain' => [
                        'name' => 'Default',
                      ]
                    ],
                    'url' => 'https://auth.cloud.ovh.net/v3/',
                    'bucket' => 'club-jeancloude-nextcloud_01',
                    'region' => 'GRA',
                    'scope' => [
                      'project' => [
                        'name' => '8966606530353673',
                        'domain' => [
                          'name' => 'Default',
                        ],
                      ],
                    ],
                  ],
                ],
              ];

            locale.config.php: |-
              <?php
              $CONFIG = [
                'default_language' => 'fr',
                'default_locale' => 'fr_FR',
                'default_phone_region' => 'FR'
              ];

            cartemembre.config.php: |-
              <?php
              $CONFIG = [
                'hide_login_form' => true,
              ];

            preview.config.php: |-
              <?php
              $CONFIG = [
                'filelocking.enabled' => true,
                'enable_previews' => true,
              ];

            proxy.config.php: |-
              <?php
              $CONFIG = [
                'overwriteprotocol' => 'https',
                'overwrite.cli.url' => 'https://app.jeancloude.club',
                'trusted_domains' => [
                  'nextcloud',
                  'app.jeancloude.club'
                ]
              ];

            mail.config.php: |-
              <?php
              $CONFIG = [
                'mail_domain' => 'jeancloude.club',
                'mail_from_address' => 'app',
                'mail_smtphost' => 'in-v3.mailjet.com',
                'mail_smtpauth' => true,
                'mail_smtpname' => '7612061780ca8cd5cf12b113cecc7dd0',
                'mail_smtppassword' => '4592d91c836ed5e292ca887052c33c15',
              ];

        ingress:
          enabled: true
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 2.11.2
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true