apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-nextcloud
  project: jeancloude.club
  source:
    chart: nextcloud
    helm:
      values: |
        image:
          tag: 23.0.0-fpm
        cronjob:
          enabled: true
        internalDatabase:
          enabled: false
        mariadb:
          enabled: true
        nginx:
          enabled: true
        nextcloud:
          host: app.jeancloude.club
          configs:
            misc.config.php: |-
              <?php
              $CONFIG = [
                'overwriteprotocol' => 'https',
                'overwrite.cli.url' => 'https://app.jeancloude.club',
                'filelocking.enabled' => 'true',
                'enable_previews' => true,
                'trusted_domains' => [
                  'nextcloud',
                  'app.jeancloude.club'
                ]
              ];

            objectstore.config.php: |-
              <?php
              $CONFIG = [
                'objectstore' => [
                  'class' => 'OC\\Files\\ObjectStore\\Swift',
                  'arguments' => [
                    'username' => 'user-KPNf2CXgFmYY',
                    'password' => 'ChaDQNt8R6CpWeaHfDNeWmzd6edhDmwW',
                    'container' => 'club-jeancloude-nextcloud-1',
                    'autocreate' => true,
                    'region' => 'GRA',
                    'url' => 'https://auth.cloud.ovh.net/v3/',
                    'tenantName' => '8966606530353673',
                  ],
                ],
              ];
        ingress:
          enabled: true
        extraEnv:
          - name: OBJECTSTORE_SWIFT_URL
            value: "https://auth.cloud.ovh.net/v3/"
          - name: OBJECTSTORE_SWIFT_AUTOCREATE
            value: "true"
          - name: OBJECTSTORE_SWIFT_USER_NAME
            value: "user-KPNf2CXgFmYY"
          - name: OBJECTSTORE_SWIFT_USER_PASSWORD
            value: "ChaDQNt8R6CpWeaHfDNeWmzd6edhDmwW"
          - name: OBJECTSTORE_SWIFT_REGION
            value: "GRA"
          - name: OBJECTSTORE_SWIFT_CONTAINER_NAME
            value: "club-jeancloude-nextcloud-1"
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 2.10.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true