apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-nextcloud
  project: jeancloude.club
  source:
    chart: nextcloud
    helm:
      values: |
        image:
          tag: 23.0.0-fpm
        cronjob:
          enabled: true
        internalDatabase:
          enabled: false
        mariadb:
          enabled: true
        nginx:
          enabled: true
        nextcloud:
          host: app.jeancloude.club
        configs:
          custom.config.php: |-
            <?php
            $CONFIG = array (
              'overwriteprotocol' => 'https',
              'overwrite.cli.url' => 'https://app.jeancloude.club',
              'filelocking.enabled' => 'true',
              'enable_previews' => true,
              'trusted_domains' =>
                [
                  'nextcloud',
                  'app.jeancloude.club'
                ]
            );
        ingress:
          enabled: true
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 2.10.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true