apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-platform
  project: default
  source:
    chart: traefik
    helm:
      values: |
        dashboard:
          enabled: true
          ingressRoute: true
        rbac:
          enabled: true
        additionalArguments:
          - "--api.dashboard=true"
          - "--log.level=INFO"
          - "--providers.kubernetesingress.ingressclass=traefik-internal"
          - "--serversTransport.insecureSkipVerify=true"
    repoURL: https://containous.github.io/traefik-helm-chart
    targetRevision: 9.1.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
