apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-velero
  project: jeancloude.club
  source:
    chart: velero
    helm:
      values: |
        proxyAddressForwarding: true
        postgresql:
          postgresqlPassword: keycloak
        ingress:
          enabled: true
          hostname: cartemembre.jeancloude.club
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 2.27.1
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true