apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  project: default
  source:
    chart: velero
    helm:
      values: |
        configuration:
          provider: community.openstack.org/openstack
          backupStorageLocation:
            bucket: velero
            prefix: jeancloude.club
          volumeSnapshotLocation:
            name: volume-snapshots
        credentials:
          name: velero-ovh-de-secret
          extraSecretRef: velero-ovh-de-secret
          extraEnvVars:
            OS_AUTH_URL: https://auth.cloud.ovh.net/v3/
            OS_PASSWORD: ChaDQNt8R6CpWeaHfDNeWmzd6edhDmwW
            OS_USERNAME: user-KPNf2CXgFmYY
            OS_PROJECT_ID: de9eaa1e9cc94734bf787165a68f4d01
            OS_REGION_NAME: DE1
            OS_DOMAIN_NAME: Default
        initContainers:
        - name: velero-plugin-openstack
          image: lirt/velero-plugin-for-openstack:v0.3.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
        backupsEnabled: true
        snapshotsEnabled: true
        schedules:
          traefik:
            disabled: false
            schedule: "0 0 * * *"
            template:
              ttl: "48h"
              includedNamespaces:
              - traefik
          keycloak:
            disabled: false
            schedule: "0 0 * * *"
            template:
              ttl: 168h # 1 week
              includedNamespaces:
              -  jeancloude-club-keycloak
          nextcloud:
            disabled: false
            schedule: "0 2 * * *"
            template:
              ttl: 168h # 1 week
              includedNamespaces:
              -  jeancloude-club-nextcloud
        upgradeCRDs: false
        
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 2.27.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true