apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jeancloude-club-velero
  project: jeancloude.club
  source:
    chart: velero
    helm:
      values: |
        provider: aws
        credentials:
          name: velero-ovh-de-secret
          secretContents: 
            cloud: |
              [default]
              aws_access_key_id=951d972e2b8d478daa89970e7cb13ec9
              aws_secret_access_key=dd0438eab0da4eb7b8ffb0dbfb310ab6
      repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 2.27.1
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true