apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: kanister-profile
  namespace: platform-kasten
  labels:
    argocd.argoproj.io/instance: kasten
    app.kubernetes.io/instance: kasten
    app.kubernetes.io/name: kasten
spec:
  type: Kanister
  kanister:
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: icekubes-aws
        namespace: platform-kasten
    location:
      type: ObjectStore
      objectStore:
        endpoint: https://s3.de.cloud.ovh.net
        name: net.pastis-hosting.icekubes
        path: kanister
        objectStoreType: S3
        pathType: Directory
        region: DE