kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: platform-cluster-scoped-resources-backup
  namespace: platform-kasten
  labels:
    argocd.argoproj.io/instance: kasten
    app.kubernetes.io/instance: kasten
    app.kubernetes.io/name: kasten
spec:
  frequency: "@hourly"
  retention:
    hourly: 24
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - platform-kasten-cluster
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: icekubes-location-objectstore-de
          namespace: platform-kasten
    - action: export
      exportParameters:
        frequency: "@hourly"
        profile:
          name: icekubes-location-objectstore-de
          namespace: platform-kasten
