apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  project: system.protect
  source:
    chart: k10
    helm:
      values: |
        rbac:
          create: true
        scc:
          create: false
        auth:
          basicAuth:
            enabled: true
            htpasswd: "tristan:{SHA}K+iK4HpzuMKnVlbTaxQSkD9/eLg="
        eula:
          accept: true
          company: "Club Jean-Cloude"
          email: jeancloude@jeancloude.club
        clusterName: Icekubes
        cluster:
          domainName: jeancloude.club
        ingress:
          create: false
          annotations:
            external-dns.alpha.kubernetes.io/hostname: kasten.jeancloude.club
        prometheus:
          server:
            enabled: true
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            persistentVolume:
              enabled: true
        grafana:
          enabled: false
        persistence:
          enabled: true
        services:
          securityContext:
            runAsUser: 0
            fsGroup: 0
        injectKanisterSidecar:
          enabled: true
          namespaceSelector:
            matchLabels:
              k10/injectKanisterSidecar: 'true'
    repoURL: https://charts.kasten.io/
    targetRevision: 4.5.6
  syncPolicy: {}