apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: k10-disaster-recovery-policy
  namespace: kasten-io
  labels:
    argocd.argoproj.io/instance: kasten
    app.kubernetes.io/instance: kasten
    app.kubernetes.io/name: kasten
spec:
  actions:
    - action: backup
      backupParameters:
        filters:
          excludeResources:
            - group: extensions
              version: v1beta1
              resource: ingresses
        profile:
          name: icekubes-location-de
          namespace: kasten-io
  retention:
    daily: 1
    hourly: 4
    monthly: 1
    weekly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io
