k10:
  global:
    persistence:
      enabled: false
  rbac:
    create: true
  scc:
    create: false
  auth:
    basicAuth:
      enabled: false
      htpasswd: "tristan:{SHA}K+iK4HpzuMKnVlbTaxQSkD9/eLg="
    oidcAuth:
      enabled: true
      providerURL: https://keycloak.pastis-hosting.net/auth/realms/pastis-hosting.net
      scopes: email groups profile
      clientID: k10
      clientSecret: wVEHH8E7znBbCv44ajP4Be4Y2N8CffI2
      usernameClaim: email
      groupClaim: groups
      redirectURL: https://k10.pastis-hosting.net/
      prompt: connect
  eula:
    accept: true
    company: "Club Jean-Cloude"
    email: jeancloude@jeancloude.club
  clusterName: Icekubes
  ingress:
    create: true
    host: k10.pastis-hosting.net
    annotations:
      external-dns.alpha.kubernetes.io/hostname: k10.pastis-hosting.net
      cert-manager.io/cluster-issuer: cert-manager-pastis-hosting-net-issuer
  prometheus:
    server:
      enabled: true
      baseURL: /k10/prometheus/
      prefixURL: /k10/prometheus/
      persistentVolume:
        enabled: false
  grafana:
    enabled: false
  services:
    securityContext:
      runAsUser: 0
      fsGroup: 0
  injectKanisterSidecar:
    enabled: true
    namespaceSelector:
      matchLabels:
        k10/injectKanisterSidecar: 'true'