apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: club-jeancloude-keycloak
  project: jeancloude.club
  source:
    chart: keycloak
    helm:
      values: |
        commonAnnotations:
          k10.kasten.io/forcegenericbackup: 'true'
          kanister.kasten.io/blueprint: postgres-bp
        proxyAddressForwarding: true
        postgresql:
          postgresqlPassword: keycloak
          postgresqlPostgresPassword: keycloak
          persistence:
            size: 1Gi
          volumePermissions:
            enabled: true
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: cartemembre.jeancloude.club
          annotations:
            external-dns.alpha.kubernetes.io/hostname: cartemembre.jeancloude.club
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.2.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
