apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: club-jeancloude-keycloak
  project: jeancloude.club
  source:
    chart: keycloak
    helm:
      values: |
        extraEnvVars:
          - name: KEYCLOAK_EXTRA_ARGS
            value: "-Dkeycloak.import=/config/realms.json"
        extraVolumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
        extraVolumes:
          - name: config
            configMap:
              name: realms
              items:
              - key: "realms.json"
                path: "realms.json"
        auth:
          createAdminUser: true
          adminUser: admin
          adminPassword: admin
        proxyAddressForwarding: true
        postgresql:
          postgresqlPassword: keycloak
          postgresqlPostgresPassword: keycloak
          persistence:
            enabled: true
            size: 1Gi
          volumePermissions:
            enabled: true
          primary:
            annotations:
              k10.kasten.io/forcegenericbackup: 'true'
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: cartemembre.jeancloude.club
          annotations:
            external-dns.alpha.kubernetes.io/hostname: cartemembre.jeancloude.club
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.2.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
