apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: system.secure
  source:
    chart: vault
    helm:
      values: |
        server:
          enabled: true
          dataStorage:
            enabled: true
            mountPath: /mnt/vault/data
          standalone:
            enabled: "true"
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "file" {
                path = "/mnt/vault/data"
              }
          ingress:
            enabled: true
            hosts:
              - host: vault.jeancloude.club
                paths: ['/']
            annotations:
              external-dns.alpha.kubernetes.io/hostname: vault.jeancloude.club
        injector:
          enabled: true
        csi:
          enabled: true
        ui:
          enabled: true
          serviceType: "ClusterIP"
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.18.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
