apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-gcp"
  namespace: {{ .Release.Namespace }}
spec:
  infra:
    credential:
      secret:
        apiVersion: v1
        kind: secret
        name: "{{ .Release.Name }}-gcp"
        namespace: {{ .Release.Namespace }}
      secretType: GcpServiceAccountKey
    type: GCP
  type: Infra