argocd:
  installCRDs: true
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argocd
          url: https://argoproj.github.io/argo-helm
      url: https://argocd.jeancloude.club
    ingress:
      enabled: true
      hosts:
        - argocd.jeancloude.club
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.jeancloude.club
      configManagementPlugins: |
        - name: kustomized-helm
          init:
            command: ["/bin/sh", "-c"]
            args: ["helm dependency build || true"]
          generate:
            command: ["/bin/sh", "-c"]
            args: ["echo \"$HELM_VALUES\" | helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $HELM_ARGS -f - --include-crds > all.yaml && kustomize build"]