argo-cd:
  installCRDs: true
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argocd
          url: https://argoproj.github.io/argo-helm
      url: https://argocd.jeancloude.club
    ingress:
      enabled: true
      hosts:
        - argocd.jeancloude.club
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.jeancloude.club
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.jeancloude.club
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.jeancloude.club