argo-cd:
  installCRDs: true
  dex:
    enabled: true
  repoServer:
    volumes:
      - name: custom-tools
        emptyDir: {}
    initContainers:
      - name: argocd-lovely-plugin-download
        image: ghcr.io/crumbhole/argocd-lovely-plugin:stable
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argocd
          url: https://argoproj.github.io/argo-helm
      url: https://argocd.jeancloude.club
      configManagementPlugins: |-
        - name: argocd-lovely-plugin
          init:
            command: ["argocd-lovely-plugin"]
            args: ["init"]
          generate:
            command: ["argocd-lovely-plugin"]
    ingress:
      enabled: true
      hosts:
        - argocd.jeancloude.club
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.jeancloude.club
    ingressGrpc:
      enabled: true
      hosts:
        - argocd.jeancloude.club
      annotations:
        external-dns.alpha.kubernetes.io/hostname: argocd.jeancloude.club