apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-pastis-hosting-net-crt
spec:
  secretName: {{ .Release.Name }}-pastis-hosting-net-secret
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Release.Name }}-pastis-hosting-net-issuer
  commonName: "*.pastis-hosting.net"
  dnsNames:
    - "*.pastis-hosting.net"