apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: BYR8IAr6DNRc5JfUZtGtirRzLJV-XMJAfwYjIKHK