apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
  namespace: club-jeancloude-nextcloud
  labels:
    argocd.argoproj.io/instance: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
stringData:
  db-username: keycloak
