apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-auth-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth-traefik.pastis-hosting.net`)
      kind: Rule
      services:
        - name: traefik-traefik-forward-auth
      middlewares:
        - name: traefik-forward-auth
  tls:
    certResolver: cloudflare