apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: traefik-forward-auth
spec:
  forwardAuth:
    # address: http://traefik-traefik-forward-auth.traefik:4181
    address: https://auth-traefik.pastis-hosting.net
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
