apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-route
spec:
  entryPoints:                      # [1]
    - https
  routes:                           # [2]
  - kind: Rule
    match: Host(`trfk.pastis-hosting.net`) && Path(`/dashboard`) # [3]
    middlewares:                    # [5]
    - name: traefik-forward-auth             # [6]
    services:
    - kind: TraefikService
      name:
  - kind: Rule
    match: Host(`trfk.pastis-hosting.net`) && Path(`/dashboard`) # [3]
    middlewares:                    # [5]
    - name: traefik-forward-auth             # [6]