apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-routes
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`trfk.pastis-hosting.net`) && (PathPrefix(`/dashboard/`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: traefik-forward-auth
    - match: PathPrefix(`/_oauth`)
      kind: Rule
      services:
        - name: traefik-traefik-forward-auth
          port: http
      middlewares:
        - name: traefik-forward-auth
  tls:
    certResolver: cloudflare