apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-route
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`trfk.pastis-hosting.net`) && Path(`/dashboard`)
    kind: Rule
    services:
      - name: dashboard@internal
        port: 80
    middlewares:
      - name: traefik-forward-auth
  - match: Host(`trfk.pastis-hosting.net`) && Path(`/api`)
    kind: Rule
    services:
      - name: api@internal
        port: 80
    middlewares:
      - name: traefik-forward-auth
