apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-admin-routes
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`trfk.pastis-hosting.net`) && Path(`/dashboard`)
    middlewares:
    - name: traefik-forward-auth
    services:
    - kind: TraefikService
      name: dashboard@internal
