apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: k10
  name: {{ .Release.Name }}-icekubes-aws
data:
  aws_access_key_id: ZGEzYWRmYzNjMWJiNGJmMTg4MGJkNDRmMTIyOTZkNDg=
  aws_secret_access_key: NmU2OGQ4Y2IyYWY4NGEzZjhiNTU4NDRkNmUzZjE1NWI=
type: secrets.kanister.io/aws
