apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-dr-secret
data:
  key: dXJWdkdrZXVVdzY0WlE2
type: Opaque
