apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    cloudflare_api_token: AgDBDDl51Y3hl7V13ggrEiw9OJOjKpswItfUeQdP7/JVnJUVd3Rzm5yNe3Lp0UZxJjIOMcjQrrubqnBRIX53WeaoRUAqfuQQWW5wgCa9eLG+lyk36XoP7qDWxICvBEsvfbCsoIVBUCFwu5E/anpWXA+l8c6cmgxM/p9oPSQ5Vu1AXe+tH5LUZ76NN5Qhfuz569lYculC3NLFu8mHc0LO7StSylYWrMHbw/mSV4TN3aaWtTUYi9CACAAeG8fgldhDF2VzgmDPRuQSpVrc4AqezJCEDitK3X+8o8VeongrudsJyBMszoW7GmTT9d6lKRFOy/uOcPkA6F6a5tzip4BFdJs9D6SM2rBFcy0B//zmLJ3HVVifbjuLVFe3qmZ2whKabSzBiRcVW3Hgj4QE/lvoMPrzQ/ozbPdjd51vDsmb4qycyb9K1JKHh7fVWota+E0Vs5jBxlkkMNxpIIybTTVTO9p6kVKLvgUCfAqVeZIQ+aVjeSzEh1fByn0srbaX3qauJwGNWD6yoLrT1SpeG7/GW7H5GIfIhPP1/xsT5xqc/dM8HmqCbfqMbhSjha2joawPzlVrMcbZtBY89Uw/kr8a4dwOnPzOnZeywi6LqeZFd0mwmMinXfPi1kUsvGoRKSDhn32bI1pMGHFyTOG0TNL0x6u9nTNxLGUEQdqAYj0TZsEKBXo4ehgaudVOtJk4MA5eSPmxVRWs2Ewk5NVfqQ37Kf13IE7j4dTW+9XfZo6RaA67GooOVJp9wEbnIA==
  template:
    data: null
    metadata:
      labels:
    {{ include "helm.labels" . | indent 6 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets
