apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    cloudflare_api_token: AgBelGd7OXZlRRxgSRn4IJTp2NOhO1z3TCFqBfpUphF7VtK9s1Yr/afma15vA8zOF5EHobXwZgkoxnokto4DAjBzwWlyMr+qqQBQ45uDvrJuNDk+VrYPP0WWBJ5M/PYQp6ZjqqM4WTeLoadjA5m84rPB9dQiRfQgp3ZFCjSI6Ld2vaOV54RWVg7xgLfMlJJD5CbYgl1TCEaj26DThsuRZjYkwmxrOm/gmG3868YblR9pf8I8Ow659FUg/LAJOLEG90aptXM8hX7UTcJCAeyXztypyPbUPYuKVonDzLlWN3FIY5QTwP4yiQeaTCTkf07dJXux+bJ081RHMK0jjhcd75hUry+qBHsbKM5PPm4VLpRHjPB+EWcpNnmqDeWeUhrOsNTBoHeQ1Zv/FonQFPDOhJ5GGrjDQHCP3wxP3XeyR3Xtx+0CmVomO4KrIkAjqvLvPfSo9seZZzV8uIuU/nG+G+elMeBw4yrERGSOaz/XPbRRqCFh4NsqNNSIZ1sUMiAROheZ3lj7xHutjiKgJIfvApvNepv0Wet6NVG6AmZwLf8oAuLYUU9/k0n40goNyjLGTrMEeMUBuU0C/hv9GalUlx5jJ6C3uM1RN4F/yFQGXCpuAvv0NTo9btTbunQ3i9OG66oDAqweNvRl8XwDTuFlV577S7ygK6DDJnWujSroytbVTLy9fRfszcBMT1BJSLZq2olb5MLP0bCHfAW1CwcKFy8Ian9BuurocG347tZY4ON3juweZU14G1IZZA==
  template:
    data: null
    metadata:
      labels:
    {{ include "helm.labels" . | indent 6 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets
