apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    cloudflare_api_token: AgCjY7cIhjYMVdlmyDtcX54cmyGVhHsqdejxUDb63DYKiuNmjKRMBwrLjA8/P2AO+s+AkGriyKL2Q/XSZ1cqEXttTumKIXm0FxSSuYCFR74HXTOexg7bQkcrbxFREvqOa9997gA1k+iJ7iZTu2vJCGTAFikoey0QMa/lqUBCuB14ETsPYLsIGnzUC+cEiXmRduI+6OFRxVo9IYji9RWepDhRHR4UTygT2rOUvj7wYsh3Mu1uQ1OkO4F8QOhTKtnl0UjeuBbW72mb8uv0vVV1p/fBQZbf83ba6AzbxV5PImpK19kfX4E9gYZcZyqugFKyc+RrjC5bOFBCbX5FI6CbFci+ootjocBVy2Pznjpfxdh2aCIQHY0/rZSn9nbSCtSiYtVeOrCBDJ3MAMp9TTxcr9YqVzsPhCJ2n4XjOW6oZTOvrPtSy1hvjiu/uqXnnDLlK1Tfey2JP1gy8py4IVIu8LIt/DLIJdz4sU1VTyxRkIroKWmR7WUVwuwv/MwRtNTI10oOYJOf3GwdXd0YOfozu/Jb3hhqEmh08YrQH5HSLEeVa641uoVtgbaKKIghPrrgCjUED9Sc40oc7QnMrnlt8UnBuyWQ69mspv6Lb17/gMIsx8cHPYzTOLTvJUdFR5Rc2pDy31dC7Q0IdUJJuFK5jctllAuR9Rp+uiV3aOZwaIWtuUOjAyOTHF4taK3PXftuKeO/kQ36KuzCg9X0waacniQmYnMCDoC2BsNL+b9RG/KLlGw9yIPCdRnWGA==
  template:
    data: null
    metadata:
      labels:
    {{ include "helm.labels" . | indent 6 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets
