apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    cloudflare_api_token: AgCW7DmfAeEtmCo2iCAfHwomJ4dj4oRwKqlbm769/O5GhNybIzjOzMWUMThlBeDlchdPdRaVyMNHPVDrT78dORAWNzzTKoWq5ryW9MOsbPDdGPvQW7YB+dQw7WLOgXePDc+AcGOh22Zvr8uBSCLVpchZemN6dVKHXhlCoHbloNhGgpCboRxij5WunUZa//ZCay+hJMqKp4lSv/4UGKMVcTUm1tXsPvsFIrWXm0a3gdkUKDPvlwYmGYnnYlq9zeX7thfhmYCsli6wOPpatKg8tABpNS/zlIzCigTZ8qhAKTQDWsnc5+xhQ1Q8ElgdARslmFyNWo6dqSp+rfSP23EaHsx0/GmF01qJxR4Wjj3ysLMzJfDFY0BslU9mmxojC7kSTvnJnr/3QzEEn8k/PnNy18PJ8VJMBnu5wv4Z6PhkVSb3avt1f3AgSeM3M/giG/9fM2tLlgGeNONgCyGw6EcC5i5vjj1uheDXEaa/ZVW9iMFUwCXayTSXxFSxP40X3neZldKeiyh4d1vvxT21orV2K9kQM91yNLhJpf4UWq9o36zuK4JkQIQpr1XI66ZVZsxYE8jgARaBRL+Ak2/y/xc/wmRf0kQbBar2BDyFkIZpmZsY8mJGWEPHhO8syrFai2xZMwAENglMmFveN4C0YyLB3zxAW5ndikjZB2Fovxxd/0uy3pIBjxvumUtRJA4WFKlj8Y83N+F5f5O417OsfsRukiMRS2Jh4t5rapTUaniJxJQOqr9E5as64D14PQ==
  template:
    data: null
    metadata:
      labels:
    {{ include "helm.labels" . | indent 6 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets
