apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secrets
spec:
  encryptedData:
    cloudflare_api_token: AgCrLqkTW63855CktNu/D9reQhajy5np3QqM2B5s+nVOAkyBwXuo570bN13sMfTSIYH4vs+zRUE1kyeQBCm1ENtsY3Bh+AU854gY3ZjaS0mR0BtKqgm8MlSB3v1/88yADXwA0aJOB+C0mp06+P8DHNzuvHCl28C1rNfExjfew0ik3eAW837u98Ncf9wOmlnYYJTwwvvF49NQgL/5O0ZKZYEV/DQSX+ogc4uX2a4LGuIeySCqFcNPou3o7oo8MpBvFSZMW2pH4U5lihD0Q8aH6ny+WySJNK/DlSR8J7mRx7FfnpqzGipxOXv4ud71XclI5jGstUqllXhGng/cIOjP5ORA2PY+bDiFwUu49w42LdpUzPH0IIKzAXEXR54kDE1sGznOp6aBgdABBPi2TFjG660vzHjDipBPKSo1r6t3LsLswA9fQNDZzMFKVYSa6V92F0/5fdvyOghAYVM6X30MxQ5lbC4khQT0vrtm+oegL4DIrvEZbsvn8D/ag4O/1xe2tVWx9lq+5sOPtTIR/iX0mE8NKSOPqq9Yq4v1SPkMzdEJCGmOvTDl+mG3/35pZ2/rYJrZ2S34KZspxrM120GKz+vpuSGzv+NSO+MnKRB8ab8bTyBXuJ7E/jbjL+M0IQyjnOAHpvHCkh+FD8FQCLpjoXQkTtEkOl0mdX798jtvM20H1s0kgne625O+Bh1Ldm59T9VrXf5Q4hi+b2GC0ibF+c5KERiJ1EJqMg2VM9aSAJqdGGF3Wn1uW/0T  template:
  template:
    data: null
    metadata:
      labels:
    {{ include "helm.labels" . | indent 6 }}
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-secrets
