apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: icekubes
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: system.deliver
  source:
    path: src/apps/
    repoURL: https://github.com/constructions-incongrues/club.jeancloude.k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
