apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-provider-openstack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: openstack-cinder-csi
    helm:
      values: |
        secret:
          enabled: true
          create: true
          name: cinder-csi-cloud-config
          data:
            cloud-config: |-
              [Global]
              auth-url=https://auth.cloud.ovh.net/v3/
              username=user-xUukp5UXvZyp
              password=vGdHXCW49Rt8BrfaDWVSWkVaSKgCMAnz
              tenant-name=8966606530353673
              domain-name=Default
              region=GRA5
        storageClass:
          enabled: true
          custom: |-
            ---
            apiVersion: snapshot.storage.k8s.io/v1beta1
            kind: VolumeSnapshotClass
            metadata:
              name: csi-cinder-snapclass
              labels:
                velero.io/csi-volumesnapshot-class: "true"
            driver: cinder.csi.openstack.org
            deletionPolicy: Delete
            parameters:
              force-create: "true"
    repoURL: https://kubernetes.github.io/cloud-provider-openstack
    targetRevision: 1.4.9
  syncPolicy:
    # automated:
    #   prune: false
    #   selfHeal: false
    syncOptions:
      - CreateNamespace=true
