kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-kube-backup
spec:
  frequency: "@daily"
  retention:
    daily: 1
    weekly: 1
    monthly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kube-system
          - kube-public
          - kube-node-lease
          - default
  actions:
    - action: backup
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: {{ .Release.Name }}-icekubes-location-objectstore-de
          namespace: {{ .Release.Namespace }}
        exportData:
          enabled: true