# https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/values.yaml
kube-prometheus:
  additionalScrapeConfigs:
    enabled: false
    type: external
    external:
      name: additional-scrape-configs
      key: configs
