apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter-crd
spec:
  destination:
    namespace: 'csi'
    server: 'https://kubernetes.default.svc'
  source:
    path: client/config/crd
    repoURL: 'https://github.com/kubernetes-csi/external-snapshotter'
    targetRevision: v5.0.0
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
