apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    chart: argo-cd
    server: https://kubernetes.default.svc
    namespace: platform-argocd
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.13.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true