kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: ph-k10
  name: k10-cluster-scoped-resources-backup
spec:
  frequency: "@daily"
  retention:
    daily: 1
    weekly: 1
    monthly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io-cluster
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: {{ .Release.Name }}-icekubes-location-objectstore-de
          namespace: ph-k10
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: {{ .Release.Name }}-icekubes-location-objectstore-de
          namespace: ph-k10
