apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: k10
  name: k10-system-reports-policy
spec:
  actions:
    - action: report
      reportParameters:
        statsIntervalDays: 1
  frequency: '@daily'
