apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-external-dns
  project: platform
  source:
    chart: external-dns
    helm:
      values: |
        policy: sync
        provider: cloudflare
        cloudflare:
          apiToken: C6l3Ek8k13OzXHmvJp413hrFXQNUHBGIb20X476x
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true