apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanister-blueprints
  namespace: platform-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kasten
  project: platform
  source:
    path: examples/stable
    repoURL: https://github.com/kanisterio/kanister.git
    targetRevision: 0.71.0
    directory:
      recurse: true
      exclude: 'foundationdb/local_cluster.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true