apiVersion: v1
kind: Secret
metadata:
  name: k10secret-icekubes-de
  namespace: kasten-io
  labels:
    argocd.argoproj.io/instance: k10
data:
  aws_access_key_id: ZGEzYWRmYzNjMWJiNGJmMTg4MGJkNDRmMTIyOTZkNDg=
  aws_secret_access_key: NmU2OGQ4Y2IyYWY4NGEzZjhiNTU4NDRkNmUzZjE1NWI=
type: secrets.kanister.io/aws
