apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-cinder-csi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: system.snapshots
  source:
  source:
    path: charts/cinder-csi-plugin
    helm:
      values: |
        csi:
          attacher:
            image:
              tag: v3.3.0
          provisioner:
            topology: "false"
            image:
              tag: v3.0.0
          resizer:
            image:
              tag: v1.3.0
          snapshotter:
            image:
              tag: v4.2.1
          snapshotController:
            enabled: true
            image:
              tag: v4.2.1
        secret:
          enabled: true
          create: true
          name: cinder-csi-cloud-config
          data:
            cloud-config: |-
              [Global]
              auth-url=https://auth.cloud.ovh.net/v3/
              username=user-xUukp5UXvZyp
              password=vGdHXCW49Rt8BrfaDWVSWkVaSKgCMAnz
              tenant-name=8966606530353673
              domain-name=Default
              region-name=GRA5
        storageClass:
          enabled: true
          custom: |-
            ---
            apiVersion: snapshot.storage.k8s.io/v1
            kind: VolumeSnapshotClass
            metadata:
              name: csi-cinder-snapclass
              labels:
                velero.io/csi-volumesnapshot-class: 'true'
            driver: cinder.csi.openstack.org
            deletionPolicy: Delete
            parameters:
              force-create: '1'
            ---
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: snapshot-controller-sa
            ---
            kind: RoleBinding
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
              name: snapshot-controller-leaderelection
              namespace: kube-system
            subjects:
              - kind: ServiceAccount
                name: snapshot-controller-sa
            roleRef:
              kind: Role
              name: snapshot-controller-leaderelection
              apiGroup: rbac.authorization.k8s.io
            ---
            kind: ClusterRoleBinding
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
              name: snapshot-controller-role
            subjects:
              - kind: ServiceAccount
                name: snapshot-controller-sa
                namespace: kube-system
            roleRef:
              kind: ClusterRole
              name: snapshot-controller-runner
              apiGroup: rbac.authorization.k8s.io

    repoURL: 'https://github.com/kubernetes/cloud-provider-openstack'
    targetRevision: v1.22.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
