apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/constructions-incongrues/net.pastis-hosting.k8s.git
      revision: HEAD
      files:
      - path: src/applications/**/config.yaml
  template:
    metadata:
      name: '{{ path.basename }}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: '{{ helm.chart }}'
        repoURL: '{{ helm.repoURL }}'
        targetRevision: '{{ helm.targetRevision }}'
        helm:
          valueFiles:
            - values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'