apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
spec:
  generators:
  - git:
      repoURL: https://github.com/constructions-incongrues/net.pastis-hosting.k8s.git
      revision: HEAD
      directories:
      - path: src/applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/constructions-incongrues/net.pastis-hosting.k8s.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'