apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Values.k10.namespace }}
  name: "{{ .Release.Name }}-cluster-scoped-resources"
spec:
  frequency: "@daily"
  retention:
    daily: 1
    weekly: 1
    monthly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io-cluster
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: "{{ .Release.Name }}-{{ .Values.profiles.infra.provider }}"
          namespace: {{ .Values.k10.namespace }}
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: "{{ .Release.Name }}-{{ .Values.profiles.location.provider }}"
          namespace: {{ .Values.k10.namespace }}
