apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Values.k10.namespace }}
  name: "{{ .Release.Name }}-disaster-recovery"
spec:
  frequency: "@daily"
  retention:
    daily: 1
    monthly: 1
    weekly: 1
    yearly: 1
  actions:
    - action: backup
      backupParameters:
        profile:
          name: "{{ .Release.Name }}-{{ .Values.profiles.location.provider}}"
          namespace: {{ .Values.k10.namespace }}
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - {{ .Release.Namespace }}
