apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-gcs"
  namespace: {{ .Values.k10.namespace }}
spec:
  locationSpec:
    credential:
      secret:
        apiVersion: v1
        kind: Secret
        name: "{{ .Release.Name }}-gcp"
        namespace: {{ .Values.k10.namespace }}
      secretType: Opaque
    objectStore:
      name: {{ .Values.profiles.location.parameters.object_store }}
      objectStoreType: GCS
      path: k10/762c2e5f-53ca-4e52-a440-60b0f3f5f58b/migration
      pathType: Directory
      region: {{ .Values.profiles.location.parameters.region }}
    type: ObjectStore
  type: Location
  