apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-cinder-csi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: system
  source:
    chart: openstack-cinder-csi
    helm:
      values: |
        secret:
          enabled: true
          create: true
          name: cinder-csi-cloud-config
          data:
            cloud-config: |-
              [Global]
              auth-url=https://auth.cloud.ovh.net/v3/
              username=user-xUukp5UXvZyp
              password=vGdHXCW49Rt8BrfaDWVSWkVaSKgCMAnz
              tenant-name=8966606530353673
              domain-name=Default
              region=GRA5
    repoURL: https://kubernetes.github.io/cloud-provider-openstack
    targetRevision: 1.4.9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
