apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: argocd-vault-replacer-credentials
type: Opaque
stringData:
  VAULT_ADDR: https://vault.pastis-hosting.net
  # VAULT_ADDR: http://vault-internal.ph-vault
  VAULT_ROLE: argocd-vault-replacer
  VAULT_TOKEN: s.GpFEzwuuG1Pwa7ikhoS2Us7c
