apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-dr"
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    key: 
  template:
    metadata:
      name: "{{ .Release.Name }}-dr"
      namespace: {{ .Release.Namespace }}