apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-dr"
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    key: AgCnAnQ2IiKtGpHK4NSGHsrJbFelZc3oKB851PvF3fe6fOv0247BNv28vaYZmRa3ApPRVnPkSmzbzvEgyxpk8mGcuKlqTbxITv8usvK4BWg1hBXtDJiWtBaRYCktfPxXubmPcXriSEr27jCOxVshXqQSBdHM2DLDLWDqXKY+Y9JIwLHMvGwf97CWKOaRtEnQXT+reBW3ypsbCCeAxBNDtBk+71SrteiK2o9gMBzDK6cuVsuZOPWV6K09DOqA48/wwaLKp2Gd3fa/goIlNvaKPye3nKJwUMSWzx1PBUObCTgTvoNebAoH1D+at/yfym3mSFnREeIx324KOmP99riTke2aghubpKcpcg8VEI00TVkYE25AOstjt+XnR79qxUfv/fZTFr82h/RKD8ntgOdZWQSWjUhnmX4Vlc6fDZyz34rlGcqiOl30xQYVJ+b9xo0A9Y8P8w2l0BCFKkLnQvfF3vJLdg6YKsG/ViFAE5U+P1oUdqL3fpgl47rZtSWD2rcDPlbS5fJSLhSikM31ymZRZcXlpyrM1AShUgXg+o1jTsXsfNnJZG6SyD84SajTYE1MxRX855e2f19N8Yle6k4zhbUGE3gXgruV0phf7rgodMA5cr4usoSZ3oaQCU0KJ+xeIg2p598CtiVZZHqluBJD6ESxXSfi5mRfP9WoIyNo3W2VGWR2ZQM8v6ZfXNjh/Nj0umcQ/m6y3vpdrXk/WISkRQ==
  template:
    metadata:
      name: "{{ .Release.Name }}-dr"
      namespace: {{ .Release.Namespace }}
