apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-dr"
  namespace: {{ .Values.k10.namespace }}
spec:
  encryptedData:
    key: AgBSz1FCXXUkWbPAq1rwnmlxHg2jvmcOeRIqpvN4TlR4mQm8EVrFmCy1BKKGkPzGOLJK9FnP6MCvJYE5BbTxIBfwwo2+jNBD7lk973ecu9MNmWqhQaER+kaXXcVGv25ikipumO8dO+3qtziHk664V8PbMPVoYek9SZhakx+pBduMWajd4+DGbMI/UWSXwuXxgbVMLi9iI5+U67b0YePcCNWuwnxVVyzPA+0TA6lF1aDN5YSq4OJGHAMvEDR8+7oWpoWB5Ww6o4bVgHDF8yPbRccR44oMNdPicmOKdTWFdszgsSLzOurz4IW5HmKsyATb7olQbqm/7qzYQY/ot3vVJkThAkPfHB5SIEpTe/qWm26JIZkbDCAxz2xROuaRaL0d8HFkw4XymbHi6m2GiH/o4BQCsXvsU4W0xT+oAxD0ilDvYNchWvJRBt+keoJus8cgYGolavFDnSqfYU8lKc2JJde7SnufaqvDsiboY4Qo9tapwbP0mtfLODe/PkZrLYWmJCGIoqvkY0tQ2mevd8bMdQV9XELlvmjtOZMBvA5tnJsiTvd3gKvwk1q4TxF8b632TvU6TKca5QktHOI+m/kHGa/6A7JCXxk6Iu44HbNd/dhKXck1b9wVIi2QHadaHYeO754ueHqwVRttYz+x//KqSB6Oiht9AnuXP9SR8vnUV46vCRn1f+uL5WqIeeEHNrL01n7g3ysaV+7GToXuSwo/eg==
  template:
    metadata:
      name: "{{ .Release.Name }}-dr"
      namespace: {{ .Values.k10.namespace }}
