apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-dr"
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    key: AgCsEx9pGSxOqJnP7svJTTbpkIO2mXyBXHAcUGGOWT+4gBp/t+nUn3Kjtt2I2lliKl19ueArKA8Y0AnBDOqdCqbHIDIcXn2RqyDq85zzGqDpHAdrRqYLCR2jBkde0V3/x/fUq7uYRTakUxXrts85RqLEPnMNKJZZU05tU4+R6CHh8SMCz6BoK1GIrR3uRNA2VchkgiQxb/XpIRGKo1D5rgndvdnGatNYhENMblOS+cITC9amO1I9ccikB+W94hlTdrQtnFilYW63V+Fc1XfSvNu+NpFWQns+k1473RtQixif8VSDwq6JqTrt5TI69/BYp8FYGOpj4tatt0xlrfOYEfMNuM5cPZh5JPLmTzzdqLEi7S7HXvuLmrZLBJgxO7/7DZ4xhp05OCxV3Q+fNydCdRdHkX+yXwsRu7HTMCRpkzT4Rn/MX/LkLVgq1K2L9xHcZMznN+b2T4ad9im9G/DP8yOAwGliCKohTpfBAbbUha6N9wQMayzALNq2srBxy3JSa/Q9KbUGEbfNq1RS1NvPW2nnJEvm7jV2VZmLiIvmhQ00EWc1BxpqlftQlaro+yl8snQAGT8Y0S3sX2wN4hFPco7PjUm7lVPP7HakVmLSSTYBHya2ae/eWnbmiFwJuR8fzZOceC/FL20jiVxaTv7JTKiCrazlC7gVMI0I5lBcntTwKz1qDucQhNeUXNIOcJHsKQCUfD1WKdB5VDtDvQaz9Q==+Y9JIwLHMvGwf97CWKOaRtEnQXT+reBW3ypsbCCeAxBNDtBk+71SrteiK2o9gMBzDK6cuVsuZOPWV6K09DOqA48/wwaLKp2Gd3fa/goIlNvaKPye3nKJwUMSWzx1PBUObCTgTvoNebAoH1D+at/yfym3mSFnREeIx324KOmP99riTke2aghubpKcpcg8VEI00TVkYE25AOstjt+XnR79qxUfv/fZTFr82h/RKD8ntgOdZWQSWjUhnmX4Vlc6fDZyz34rlGcqiOl30xQYVJ+b9xo0A9Y8P8w2l0BCFKkLnQvfF3vJLdg6YKsG/ViFAE5U+P1oUdqL3fpgl47rZtSWD2rcDPlbS5fJSLhSikM31ymZRZcXlpyrM1AShUgXg+o1jTsXsfNnJZG6SyD84SajTYE1MxRX855e2f19N8Yle6k4zhbUGE3gXgruV0phf7rgodMA5cr4usoSZ3oaQCU0KJ+xeIg2p598CtiVZZHqluBJD6ESxXSfi5mRfP9WoIyNo3W2VGWR2ZQM8v6ZfXNjh/Nj0umcQ/m6y3vpdrXk/WISkRQ==
  template:
    metadata:
      name: "{{ .Release.Name }}-dr"
      namespace: {{ .Release.Namespace }}
