apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: "{{ .Release.Name }}-dr"
  namespace: {{ .Values.k10.namespace }}
spec:
  encryptedData:
    key: AgCHwSXD5D57hI01IakIECy7lPalwssyIpGEtJoD8+djLpy+tgIr+KJcw0hqfv/unhCQ/WdhiuTHrAlEuHpJCDEiTJMfZADzM8YOFfQnN1B2MpkOiM8H3GSWPmcfNTrh8XExVUZcTcy7kjl3WwSR2DS6bX8CSO91OYc11tScjWGIlVrGawIxbwHfwgR1PBZVit4P9XCo8BHvV8u1JkuaUd55cnUOp+QHU/z+nO9A6vXyjLKkqIRN8k36wP53DcDw+q9VdEv0F2Xg+UZQQ20TYESVbm9pZgygKX1GFyYrjs30fGz2yvk2Mo6sZcLUqtFtF+G7kvN1YLeNEcXNUy5tZ8DmBEs77/vfk+0bxPzXLHWlHcq0/0U8prGSBX9G+dHMmIh4D1aC3D2XojTBlH65emTssh9GgSxWtYPa6rhwCBJs6z88gO9IpnKDmHmyOQ9tm7OZsvYkB5I9ofS4kMDxSgRYQwECXQZfG5apBuDxrQt2LvQsO5QpLcZ0TOosdjoEz3dUlvOCjWDeNm4ONT2EAcSFaWvCHv2WP6ntcci+ITpmMGzk53L1AXB4r+F5NRTBTr/rAB0WRDFM5hn1/5wt3XGjt/nsVnVG3TO93/H1cr3F6zZ+4l8tzLAo3aBjK6U7ZYhU7kIw+MaiHQSID5Uu+AWjuN7VAdRshuOxyOeaVWHkBU9teV3TRMQlmFFxUvkV6JoVATdTafHgSJOcr4yEeQ==
  template:
    metadata:
      name: "{{ .Release.Name }}-dr"
      namespace: {{ .Values.k10.namespace }}
