apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: k10-oidc-auth
  namespace: {{ .Values.k10.namespace }}
spec:
  encryptedData:
    client-id: AgBiNE2XaN79V6dKy5vCU1raFbo0k3wXGxqoYSEaO74jVwOCTd7dpQhq+PHKAFMgxUcfRmJstni6XQDwjoxM1pUBDo49FkLg/YvSgo9XFsGcQWg5xoEXaeWXp5il7ICUdZl4GP6FaFqvwYJ0lQvxgU/8m7QQVMLxv2tRTMJQ7w7nhsdre8mhe4ZBzlf94Ys52Rua+/ED8/2B8miWl9eiEajH83OkojaAQd82dNHAb8YTo/j6pFj3wU11LPgvBMYBjvvx/GxyLrPnU4CgY5m5QxxEw29Xn5byausFlQ6GdePdKKGvf8BhoipoRdx9nE6+pse7kU70RAmLKR4nMAKbTkHG4wmXq7MpPUWZ32xTtIx4cRL/T7xHvB4Ksbrl6NxHhyjeXbhZOf4AcYMJQQqExzV7E9HjKZVRkBqLnhbwDkth0rpiQI5NpeNi8dWrwVcDkZFuYoPquAB+RilVzWmX2FBR2QFzClMiKzK8MpC+3N8019rcCTigt5SUPBQD+u+/LCYLZ+dRqus1fHe67UbQ7oCvL4jApp1X5d4Vsr1cbMDDyav9l+259JoDX/4LdWXdVZ/4UFXwsb6SHWO3qsEQ7IWiAa431tXf1Q/vpscB+mGk9X+jD2rQAPb69mdcOdp3l3j8sHn8pbu5mAJP5iYzIzSFHjRF+P9XRaYPnINSZJifzvy4ybMMPX3JBuCe0jqzX+KI7jE=
    client-secret: AgCzRLgob9XNXgVpqrRkzBzzpDH6tFsGg6zuk9HhtmUZg27nET/OnMZHj6gGg7aYdljQpI1V6GG8YJTWqncEbH/1BNYZAb2YuTab7N+J+yBDFmpsEljVKNOskamI1xjFdw5xJkyRz33irbEhyVXpPwOLDmcUyZIIdrfFhjz/kKg28oWfRvLk3qJ6GKHHbIBBIocST7d7LQPV1QEsZndD5iwf8ZqDit4BGsxrQSvrfUoyVK/0llaYoqZRv4lzd+vpmHr5/OiEX2X2xfVOcq2q6jH1J7FKtSQ3+9H+sss4MugWebecujwCwuRwEYpQ+uM8ADKVYhgeozK7ENKJvAbtRe/8LSprH77W1Dztk/1EnztJK8+cFQHkiTg0hS03cTlubXdYWo++HyubdTQNtEH2WVlyAf3EkAnrqKvNh7g0HT3D93K0wgdETcEy2jM/p+rbPnQZA5XbhYF3w6oehMFryKeX4+n2pisxK1Ps7jERBHl3+W9pZoKDyZcWT/GrH8PtSEjrEh2zIofRy3xfo7pp22j7FXIVhD3rdT+CFzMh6qtYk7r59ltdSFqH03zk+ctbWJNoSRD55zm34JmBrpdZV7cXP9T+YZAshww06Bw6q4OpPE1bsuvKvmpunD5arlqKQrtEq0lJyb0O2uQePQujzIofDCzOPjpHC7wVCYYgKtZmD7gF6R6CLYG+JgecRBCcUdEMZ+xByqqWcCb0pvbLPpUE/hq3RX11Kl2KT2ib/h0eqw==
  template:
    metadata:
      name: k10-oidc-auth
      namespace: {{ .Values.k10.namespace }}²²